/**
 * This file is provided by Facebook for testing and evaluation purposes
 * only. Facebook reserves all rights not expressly granted.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * FACEBOOK BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
 * AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

var keyMirror = require('keymirror');

module.exports = {

  ActionTypes: keyMirror({

    AUTHENTICATION_SUCCESS: null,

    RECEIVE_DEPLOYMENTS_ALL: null,
    RECEIVE_DEPLOYMENT_SUCCESS: null,
    RECEIVE_DEPLOYMENT_FAILED: null,

    DEPLOY_SETUP_APP: null,
    DEPLOY_DELETE: null,
    DEPLOY_DELETE_SUCCESS: null,
    INSTALL_APP: null,
    INSTALL_CANCEL: null,

    RECEIVE_APPLIBRARY_ALL: null
  })

};
